# Generated by Django 5.0.2 on 2024-03-09 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=100)),
                ('distance_travelled', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('images', models.ImageField(default='default.png', upload_to='')),
                ('mileage', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('available_status', models.CharField(choices=[('B', 'Booked'), ('NB', 'Not Booked')], default='NB', max_length=2)),
                ('insurance_status', models.CharField(choices=[('U', 'Updated'), ('NU', 'No Update')], default='NU', max_length=2)),
                ('fuel', models.CharField(choices=[('P', 'Petrol'), ('D', ' Diesel')], default='D', max_length=1)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
