# Generated by Django 5.0.2 on 2024-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_renthistory_delete_renting'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='RentHistory',
        ),
    ]
