# Generated by Django 5.0.3 on 2024-04-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_canceledorders_faq_location_vehicle_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fullFuel',
        ),
    ]
