# Generated by Django 5.0.3 on 2024-04-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_remove_order_fullfuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='images',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
